"""empty message

Revision ID: 060af29a39f7
Revises: 85756dcf2ae2
Create Date: 2021-12-27 13:23:11.553741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060af29a39f7'
down_revision = '85756dcf2ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_piloto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kg_piloto', sa.Float(), nullable=True),
    sa.Column('kg_piloto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kg_piloto_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo_pobre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kg_pobre', sa.Float(), nullable=True),
    sa.Column('kg_pobre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kg_pobre_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumo_rico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kg_rico', sa.Float(), nullable=True),
    sa.Column('kg_rico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kg_rico_id'], ['ensaios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ensaios', sa.Column('volume', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ensaios', 'volume')
    op.drop_table('consumo_rico')
    op.drop_table('consumo_pobre')
    op.drop_table('consumo_piloto')
    # ### end Alembic commands ###
