"""empty message

Revision ID: 29f367533ec7
Revises: 060af29a39f7
Create Date: 2021-12-28 00:27:39.874703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f367533ec7'
down_revision = '060af29a39f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cp_piloto', sa.Column('idade', sa.Integer(), nullable=True))
    op.add_column('cp_pobre', sa.Column('idade', sa.Integer(), nullable=True))
    op.add_column('cp_rico', sa.Column('idade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cp_rico', 'idade')
    op.drop_column('cp_pobre', 'idade')
    op.drop_column('cp_piloto', 'idade')
    # ### end Alembic commands ###
