"""empty message

Revision ID: 71892046cb51
Revises: f18b6856301d
Create Date: 2021-12-26 15:38:38.927879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71892046cb51'
down_revision = 'f18b6856301d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teste', sa.Column('teste_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teste', 'ensaios', ['teste_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teste', type_='foreignkey')
    op.drop_column('teste', 'teste_id')
    # ### end Alembic commands ###
