"""empty message

Revision ID: 85756dcf2ae2
Revises: c7650ecda8f4
Create Date: 2021-12-26 18:50:18.794660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85756dcf2ae2'
down_revision = 'c7650ecda8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teste', sa.Column('cm', sa.Float(), nullable=True))
    op.add_column('teste', sa.Column('am', sa.Float(), nullable=True))
    op.add_column('teste', sa.Column('bm', sa.Float(), nullable=True))
    op.add_column('teste', sa.Column('cacr', sa.Float(), nullable=True))
    op.add_column('teste', sa.Column('aacr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teste', 'aacr')
    op.drop_column('teste', 'cacr')
    op.drop_column('teste', 'bm')
    op.drop_column('teste', 'am')
    op.drop_column('teste', 'cm')
    # ### end Alembic commands ###
