"""empty message

Revision ID: babe621ab6f6
Revises: 56339aa19d7e
Create Date: 2022-01-13 10:49:31.719687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'babe621ab6f6'
down_revision = '56339aa19d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultados', sa.Column('idade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resultados', 'idade')
    # ### end Alembic commands ###
